### PR TITLE
Treat `*` character as null indicator of numeric field

### LINKED ISSUE #11: DBF * in numeric field
Hi,
I was passed a simple shp file made by QGIS.  It errors out on reading in.  A quick debug finds a string of * in the numeric ID field.  We added the following quick fix: 

readval

I wonder if you have a better approach that could be folded in to the repo?  File attached.
[WallaceMonument.zip](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/files/10154052/WallaceMonument.zip)

PS is there a nuget for this repo? couldn't locate it on last look.

thanks in advance, and cheers for the work, Matt

### PR DESCRIPTION
**Pull request by KubaSzostak**
QGIS reads numeric fields filled with `*` character. Esri also does not complain. Now [NetTopologySuite.IO.Esri](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri) will also support it. Fix #11.

### CODE REVIEW

**Review by DGuidi — APPROVED** [review]

**Comment by FObermaier** [comment]
Here is how GDAL/OGR evaluates a dbase field for NULL:
https://github.com/OSGeo/gdal/blob/master/ogr/ogrsf_frmts/shape/dbfopen.c#L1102-L1143

Is that conformant to how we do it here?

**Comment by DGuidi** [comment]
> Is that conformant to how we do it here?

looks the same handling implemented here to me

**Comment by KubaSzostak** [comment]
> Is that conformant to how we do it here?

1. It's pretty  much the same for numeric and character fields . 
2. Additionally I will add missing `"00000000"` check fot Date fields. 
3. For Logical fields they check only for `'?'`. In our code everything but `TtYy` and `FfNn` is treated as NULL. Should I make it conformant with GDAL?

**Comment by FObermaier** [comment]
> 2. Additionally I will add missing `"00000000"` check for Date fields. 

That is good.
> 3. For Logical fields they check only for `'?'`. In our code everything but `TtYy` and `FfNn` is treated as NULL. Should I make it conformant with GDAL?

I'd say so, this way we reduce the chance of having to fix it later on. I __assume__ that everything else beside `"TtYy"` and `"?"` is treated as false in GDAL/OGR.

**Comment by KubaSzostak** [comment]
> I assume that everything else beside "TtYy" and "?" is treated as false in GDAL/OGR.

I don't know how it's treated in GDAL. The `TtYy` and `FfNn` is my ideat to get logical value from character not always within DBASE specification. I don't know how GDAL is dealing with this. I will check it and make it conformant with GDAL.

**Comment by FObermaier** [comment]
It seems like GDAL/OGR Shapefile driver does not do any explicit conversion to bool and just passes a pointer ot the character. In QGIS you can't create a Dbase field of type logical/bool. So we are a bit on our own.

I'd say we can safely convert `TtYy1` to `true` and any other value to `false`. `?`  is null. Maybe instead of just `1` we can treat any number character != 0 as `true`.

According to https://www.clicketyclick.dk/databases/xbase/format/data_types.html#DATA_TYPES
* `"TtYy"` -> `true`
* `"FfNn"` -> `false`
* `"?"` (|| `" "`) -> null

**Review by FObermaier — COMMENTED** [review]
I'm OK with this for the numeric field.

**Pull request merged**
