### PR TITLE
Fix decimal parsing issue for scientific notation in DbfNumericDecimalField (#57)

### LINKED ISSUE #57: Error processing numeric fields in scientific notation with `DbfNumericDecimalField`
**Description:**

I am encountering an issue while using the `NetTopologySuite.IO.Esri` library to read shapefiles that contain numeric fields in scientific notation. The library fails to convert these values to the `decimal` type due to the string formatting.

**Problem Details:**

When processing numeric fields with values like `"9.095630227029324e-05           "`, the current method `decimal.Parse(s, CultureInfo.InvariantCulture)` cannot correctly interpret the string due to the scientific notation (`e`). This results in the following exception:

**Relevant Code:**

Here is an example of code that triggers the error:

```csharp
string numericString = "9.095630227029324e-05           ";
decimal decimalValue = decimal.Parse(numericString, System.Globalization.CultureInfo.InvariantCulture);
```

**Suggested Solution:**

The `decimal.Parse` method should be used with `NumberStyles.Float` to support scientific notation. The corrected code would be:
```csharp
decimal decimalValue = decimal.Parse(numericString, System.Globalization.NumberStyles.Float, System.Globalization.CultureInfo.InvariantCulture);
```

**Affected Class:**

The issue occurs in the `DbfNumericDecimalField` class in the `NetTopologySuite.IO.Esri.Dbf.Fields` namespace.

### PR DESCRIPTION
**Pull request by DiegoNetoMartins**
This PR addresses the issue with decimal parsing in scientific notation described in issue #57 .

Fixes #57

### CODE REVIEW

**Comment by KubaSzostak** [comment]
Hi @DiegoNetoMartins, thank you for identifying this issue and suggesting a fix. Your proposed modification looks solid. To ensure comprehensive coverage, could you please add a unit test to validate this change? You might find it helpful to follow the existing test for the [Issue049](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/develop/test/NetTopologySuite.IO.Esri.Test/Issues/Issue049.cs), which also relates to the `DbfNumericDecimalField`. Looking forward to your update!

**Comment by DiegoNetoMartins** [comment]
> Hi @DiegoNetoMartins, thank you for identifying this issue and suggesting a fix. Your proposed modification looks solid. To ensure comprehensive coverage, could you please add a unit test to validate this change? You might find it helpful to follow the existing test for the [Issue049](https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/blob/develop/test/NetTopologySuite.IO.Esri.Test/Issues/Issue049.cs), which also relates to the `DbfNumericDecimalField`. Looking forward to your update!

Hi @KubaSzostak ,

Thank you for your feedback. I have added a unit test to validate the change related to DbfNumericDecimalField. You can find the changes in the following commit: https://github.com/NetTopologySuite/NetTopologySuite.IO.Esri/pull/58/commits/d1f50ed39a925e810c3c0cb4f438ccf83ae729cf

Please let me know if there are any further adjustments needed.

Looking forward to your review!

Best regards,
Diego

**Comment by KubaSzostak** [comment]
Thank you @DiegoNetoMartins for fixing the issue and and for adding the unit test. The changes look great, and the test case covers the modification well. Looking forward to any future collaborations!

**Comment by DiegoNetoMartins** [comment]
> Thank you @DiegoNetoMartins for fixing the issue and and for adding the unit test. The changes look great, and the test case covers the modification well. Looking forward to any future collaborations!

Hi @KubaSzostak, thanks for the feedback! Could you let me know when these updates will be included in the NuGet package?

**Comment by KubaSzostak** [comment]
@FObermaier, can we push the latest fixes to the NuGet repository?

**Comment by FObermaier** [comment]
@KubaSzostak, done.

**Pull request merged**
